### ISSUE TITLE
Request: Use http instead of express

### ISSUE THREAD

**Issue by hesselbom** [krasimir/now-lambda-runner#2]
One of the caveats listed in the README is that some methods of express won't be available in production because Zeit uses Node's http module.

Would it perhaps be possible to modify this package to use http as well? To avoid possible confusion when going from development to deploy.

**Comment by krasimir** [comment]
@hesselbom exactly what I was thinking today. It makes total sense and I'll do it.

**Comment by krasimir** [comment]
`3.0.0` released and does not use express. It relies on the native `http` module.

**Comment by appler1009** [comment]
I think we should update the README to reflect this fix. README still says the lambda runner is based on Express.
